#!/bin/bash
set -eux

if [[ "${TRAVIS_EVENT_TYPE}" == "push" ]]; then
  if [[ ${NUM_PARENTS} == 1 ]]; then
    echo push
  else
    echo pr-merge
  fi
elif [[ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]]; then
  echo pr
elif [[ "${TRAVIS_EVENT_TYPE}" == "api" ]]; then
  # do not build
  echo ""
elif [[ "${TRAVIS_EVENT_TYPE}" == "cron" ]]; then
  echo push
fi
